### ISSUE TITLE
infra.UserPersistence is broken!

### ISSUE THREAD

**Issue by VictorKoehler** [LuyzaDomingos/MPS-lab01#6]
Fix it!

**Comment by LuyzaDomingos** [comment]
Fixed!

**Comment by VictorKoehler** [comment]
https://github.com/LuyzaDomingos/MPS-lab01/commit/60812b9354f6fe1ac48edbb008cc5a4600699c74#commitcomment-37795049

Não feche esta issue até eu ~ficar satisfeito~ dar um veredito sobre as mudanças que ainda precisam ser feitas.

**Comment by LuyzaDomingos** [comment]
Issue fixed.
